# Generated by Django 4.2.2 on 2023-06-13 07:38

from django.conf import settings
import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('app_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='App name')),
                ('model_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model name')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_instance', models.JSONField(verbose_name='Object instance')),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'Update'), (2, 'Create'), (3, 'Delete')], default=1, verbose_name='Action type')),
                ('action_tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Action tag')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('from_email', models.EmailField(blank=True, max_length=75, verbose_name='From email')),
                ('recipients', models.TextField(blank=True, null=True, verbose_name='Recipients')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
            ],
            options={
                'verbose_name': 'email Log',
                'verbose_name_plural': 'email Log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session key')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('path', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Path')),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remote address')),
                ('ua_string', models.TextField(blank=True, null=True, verbose_name='UA string')),
                ('hash', models.CharField(max_length=32, unique=True, verbose_name='Hash')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_log', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Visit Log',
                'verbose_name_plural': 'Visit Log',
                'ordering': ('-created_at',),
            },
        ),
    ]
