# Generated by Django 4.2.2 on 2024-05-04 17:30

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('app_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='App name')),
                ('model_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Model name')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_instance', models.JSONField(verbose_name='Object instance')),
                ('action_type', models.CharField(choices=[('UP', 'Update'), ('CR', 'Create'), ('DE', 'Delete')], default='UP', max_length=2, verbose_name='Action type')),
                ('action_tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Action tag')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Log',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
