FROM jwilder/nginx-proxy:1.5.1-alpine

COPY certs/server.crt /etc/nginx/certs/
COPY certs/server.key /etc/nginx/certs/
COPY conf.d/custom.conf /etc/nginx/conf.d/custom.conf
COPY conf.d/compression.conf /etc/nginx/conf.d/compression.conf
COPY vhost.d/default /etc/nginx/vhost.d/default