# Generated by Django 4.2.2 on 2024-05-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('owner', models.CharField(max_length=128, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('code', models.CharField(max_length=50000, verbose_name='Code')),
                ('version', models.CharField(max_length=128, verbose_name='Version')),
                ('owner', models.CharField(max_length=128, verbose_name='Owner')),
                ('parent_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_algorithm', to='endpoints.endpoint', verbose_name='Parent Endpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLAlgorithmStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('status', models.CharField(max_length=128, verbose_name='Status')),
                ('active', models.BooleanField(verbose_name='Active?')),
                ('created_by', models.CharField(max_length=128, verbose_name='Created By')),
                ('parent_mlalgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_algorithm_status', to='endpoints.mlalgorithm', verbose_name='Parent ML Algorithm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLAlgorithmRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('input_data', models.CharField(max_length=10000, verbose_name='Input Data')),
                ('full_response', models.CharField(max_length=10000, verbose_name='Full Response')),
                ('response', models.CharField(max_length=10000, verbose_name='Response')),
                ('feedback', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Feedback')),
                ('parent_mlalgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_algorithm_request', to='endpoints.mlalgorithm', verbose_name='Parent ML Algorithm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=10000, verbose_name='Title')),
                ('created_by', models.CharField(max_length=128, verbose_name='Created By')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('summary', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Summary')),
                ('parent_mlalgorithm_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_algorithm_1', to='endpoints.mlalgorithm', verbose_name='Parent ML Algorithm 1')),
                ('parent_mlalgorithm_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_algorithm_2', to='endpoints.mlalgorithm', verbose_name='Parent ML Algorithm 2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
