FROM python:3.13.2-bookworm

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/logs
RUN mkdir -p /usr/src/app/staticfiles

RUN apt-get update && apt-get install -y \
    # essential build tools
    build-essential \
    # tools for binary manipulation
    binutils

WORKDIR /usr/src/app

COPY . .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt
